development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 10
        connect_timeout: 10
        socket_timeout: 10
        max_pool_size: 20
        min_pool_size: 5
        max_idle_time: 600
        wait_queue_timeout: 10
        heartbeat_interval: 60
        log_level: :warn
test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 5
        max_pool_size: 5
        min_pool_size: 2
        wait_queue_timeout: 5
        connect_timeout: 5
        socket_timeout: 5

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        server_selection_timeout: 30
        connect_timeout: 30
        socket_timeout: 30
